### ISSUE TITLE
Please update to resolve dependency alerts.

### ISSUE THREAD

**Issue by joshgoebel** [highlightjs/highlightjs-alan-if#4]

**Comment by tajmone** [comment]
_Mea culpa_ ... I've procrastinating for ages the fixes! I've been spread thin across various projects and couldn't find the time to read the documentation of the new system.

I'll try to fix this in the course of the week. (thanks for reminding me)

**Comment by tajmone** [comment]
@yyyc514, I've solved the dependencies alert by simply dropping from `package.json` the whole `"devDependencies"` section and deleting the `package-lock.json` file altogether. By looking at other third party syntaxes (as standalone repos) I figured out that with the new integration system these are not necessary, since the syntax will be dealt with by the main highlight.js package.

Since the introduction of the new system, with syntaxes stored as independent repos, I've never managed to catch up on how it works.

I remember the rather long discussion that took place at highlightjs/highlight.js#2328, but I couldn't keep up with it due to time constraints (and looking back at it today, it's _really_ long indeed).

The official [dev docs] don't appear to cover the new system either, and peeking at the various third party syntaxes hosted as independent repositories I fail to see a uniform way to structure the repositories' folders, settings, etc.

I'm also getting an auto-generated issue (#1) requesting to activate Greenkeeper — again, I didn't see it being used by other third party syntaxes.

I personally liked more the previous system, where syntaxes were added to the main repository, and having been unable to follow the transition to the new system step by step I now find myself a bit lost regarding how the new system requires syntax repositories to be structured, automated, and even used.

I can't find any documentation on how to integrate syntax repositories into custom HLJS builds for the browser — the [dev docs] don't seem to mention this, and the highlight.js repo's Wiki is empty.

Could you please add some easy to reach guidelines on the main repository Wiki, providing basic setup and usage tips, and links to further documentation and sample syntaxes one should take as example?

Thanks



[dev docs]: https://highlightjs.readthedocs.io/

**Comment by joshgoebel** [comment]
>  the new integration system these are not necessary, since the syntax will be dealt with by the main highlight.js package.

 Yep. Exactly!

> I'm also getting an auto-generated issue (#1) requesting to activate Greenkeeper 

Shouldn't matter if you have no real actual dependencies of your own. (technically most simple grammars should need almost zero dependencies)

>  providing basic setup and usage tips

Please see https://github.com/highlightjs/highlight.js/blob/master/extra/3RD_PARTY_QUICK_START.md and let us know if that helps.  It should have all the basics.
